language: python
sudo: required
services:
- docker
python:
- 3.6
branches:
  only:
  - /.*/
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
install:
  - docker-compose build
  - pip install -r requirements-dev.txt
before_script:
  # We will run a postgres service into docker, so wee need to stop the postgres service
  - sudo service postgresql stop
script:
  - docker-compose run api coverage run manage.py test
  - docker-compose run api pycodestyle --config=.pycodestylerc .
after_success:
  - docker-compose run -e TRAVIS_JOB_ID -e TRAVIS_BRANCH -e TRAVIS api coveralls
  - python utils/write_secure_env.py
  - bash utils/deploy.sh
env:
  global:
    -SECRET