# Generated by Django 2.2.5 on 2020-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20200203_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='information_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='information_text_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='label_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='label_fr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation of the answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation of the answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='label_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='label_fr',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
