# Generated by Django 2.2.5 on 2020-02-06 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20191226_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='qr_code_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Code Token'),
        ),
        migrations.CreateModel(
            name='ArtworkVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Participant email')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Visit Date')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='artwork.Artwork', verbose_name='Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('media_type', models.CharField(max_length=250, verbose_name='Madia Type')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='artwork.Artwork', verbose_name='Artwork')),
            ],
        ),
    ]
