# Generated by Django 2.2.5 on 2020-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20200206_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='artist',
            name='country_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='artist',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='first_name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='artworkmedia',
            name='detail_en',
            field=models.TextField(blank=True, null=True, verbose_name='Detail'),
        ),
        migrations.AddField(
            model_name='artworkmedia',
            name='detail_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Detail'),
        ),
        migrations.AddField(
            model_name='artworktype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Artwork Type'),
        ),
        migrations.AddField(
            model_name='artworktype',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Artwork Type'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Partner Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Partner Name'),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Place Name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Place Name'),
        ),
    ]
