# Generated by Django 2.2.5 on 2020-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_auto_20200206_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('places', models.FileField(upload_to='', verbose_name='Places file')),
                ('artwork_types', models.FileField(upload_to='', verbose_name='Artwork Types file')),
                ('artists', models.FileField(upload_to='', verbose_name='Artists File')),
                ('artworks', models.FileField(upload_to='', verbose_name='Artworks File')),
            ],
        ),
    ]
