# Generated by Django 2.2.5 on 2020-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_updatedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedata',
            name='places_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
