# Generated by Django 2.2.5 on 2020-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_auto_20200207_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='first_name_fr',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name_fr',
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='creation_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='link_en',
            field=models.TextField(blank=True, null=True, verbose_name='Url to partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='link_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Url to partner'),
        ),
        migrations.AddField(
            model_name='place',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='partner_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='partner_type_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Url to partner'),
        ),
    ]
