# Generated by Django 2.2.5 on 2020-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_artwork_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='index_itinerary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Index Itinerary'),
        ),
    ]
