# Generated by Django 2.2.5 on 2020-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_artwork_index_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='off_road',
            field=models.BooleanField(default=True, verbose_name='Off road'),
        ),
    ]
