# Generated by Django 2.2.5 on 2020-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_partner_off_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='off_road',
        ),
        migrations.AddField(
            model_name='artwork',
            name='off_road',
            field=models.BooleanField(default=True, verbose_name='Off road'),
        ),
    ]
