# Generated by Django 2.2.5 on 2020-03-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_auto_20200221_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatedata',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='updatedata',
            name='artwork_types',
        ),
        migrations.RemoveField(
            model_name='updatedata',
            name='artworks',
        ),
        migrations.RemoveField(
            model_name='updatedata',
            name='places',
        ),
        migrations.AddField(
            model_name='updatedata',
            name='choices_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='event_types_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='events_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='questions_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
